name: Ayoub TV Persistent Stream

on:
  workflow_dispatch:
    inputs:
      m3u8_url:
        description: 'رابط البث (m3u8)'
        required: true
        default: ''
      stream_key:
        description: 'Facebook Stream Key'
        required: true
        default: ''

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Launch Live Stream
        run: |
          echo "📡 جاري إطلاق البث المباشر لـ فيسبوك..."
          ffmpeg -re -i "${{ github.event.inputs.m3u8_url }}" \
            -c:v copy \
            -c:a aac \
            -b:a 128k \
            -f flv \
            "rtmps://live-api-s.facebook.com:443/rtmp/${{ github.event.inputs.stream_key }}"
